controller_list:
- name: "tez_1_moveit_lab"
  action_ns: follow_joint_trajectory
  type: FollowJointTrajectory
  joints:
  - kr210_1_linear_axis_joint
  - kr210_1_joint_1
  - kr210_1_joint_2
  - kr210_1_joint_3
  - kr210_1_joint_4
  - kr210_1_joint_5
  - kr210_1_joint_6
  
- name: "tez_2_moveit_lab"
  action_ns: follow_joint_trajectory
  type: FollowJointTrajectory
  joints:
  - kr210_2_linear_axis_joint
  - kr210_2_joint_1
  - kr210_2_joint_2
  - kr210_2_joint_3
  - kr210_2_joint_4
  - kr210_2_joint_5
  - kr210_2_joint_6
