action_name: "/tez_1_moveit_lab/follow_joint_trajectory"
mqtt_topic: "/robot_1/joint_trajectory"
#broker_address: 172.31.1.11
broker_address: 192.168.12.204
#broker_address: "localhost"
port: 1883
client_id: "robot1/mqtt_converter"
rate: 100

robot_hw_ns: "/robot1_mqtt_hw"

robot_joint_names: 
- kr210_1_linear_axis_joint
- kr210_1_joint_1
- kr210_1_joint_2
- kr210_1_joint_3
- kr210_1_joint_4
- kr210_1_joint_5
- kr210_1_joint_6




