robot1_mqtt_hw:
  type: "cnr/control/MQTTRobotHW"
  appenders      : [file, screen]
  levels         : [trace, info]
  pattern_layout : "[%5p][%d{HH:mm:ss,SSS}][%50M:%04L][%24c] %m%n"
  file_name      : mqtt_hw
  sampling_period: 0.01
  diagnostic_period: 0.1
  maximum_missing_cycles: 100
  feedback_joint_state_timeout: 10

  joint_names: 
  - kr210_1_linear_axis_joint
  - kr210_1_joint_1
  - kr210_1_joint_2
  - kr210_1_joint_3
  - kr210_1_joint_4
  - kr210_1_joint_5
  - kr210_1_joint_6


  base_link: "linear_axis"
  tool_link: "KR210_1_A6"
  robot_description_param: /robot_description
  robot_description_planning_param: /robot_description_planning
  kin_update_period: 0.1

  initial_position: [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0]
  
  use_delta_target_pos: true
  delta_pos_from_start: true
  
  #--- MQTT ---
  
  client_id: "MQTT_HW"
  host: 169.254.57.188    # drapebot
  #host: localhost
  port: 1883
  
  feedback_mqtt_topic: "robot1/feedback"
  out_feedback_mqtt_topic: "ITR_feedback"
  command_mqtt_topic:  "robot1/command"
  nominal_trajectory_topic: /robot1/joint_pos_target
  # --- end ---
  

  remap_source_args:
  - "/robot1_mqtt_hw/js_pub_r1/joint_states"
  remap_target_args:
  #- "/robot1/joint_states"  # TODO: se mai sara disponibile topics_hw
  - "/joint_states"

  js_pub_r1:
    type: cnr/control/JointStatePublisher
    controlled_joints: all
    kin_update_period : 0.1


  p_j_r1:
    type: cnr/control/OpenLoopPositionController
    setpoint_topic_name: /robot1/joint_pos_target
    controlled_joints: all
    kin_update_period : 0.1







robot1_deformation_hw:
  type: cnr/control/TopicRobotHW
  appenders: [file, screen]
  levels: [trace, info]
  pattern_layout: "[%5p][%d{HH:mm:ss,SSS}][%M:%L][%c] %m%n"
  file_name: "robot1_deformation_hw"
  
  joint_names:   
  - kr210_1_linear_axis_joint
  - kr210_1_joint_1
  - kr210_1_joint_2
  - kr210_1_joint_3
  - kr210_1_joint_4
  - kr210_1_joint_5
  - kr210_1_joint_6

  base_link: "linear_axis"
  tool_link: "KR210_1_A6"
  robot_description_param: /robot_description
  robot_description_planning_param: /robot_description_planning

  feedback_joint_state_topic: /joint_states
  command_joint_state_topic:  /robot1/joint_pos_target
  sampling_period: 0.01
  diagnostic_period: 0.1
  feedback_joint_state_timeout: 20
  maximum_missing_cycles: 100

  deformation_ctrl_r1:
    type: "cnr/control/DeformationCtrl"
    controlled_joints: all
    kin_update_period: 0.008
    
    use_cartesian_reference: false                 # are you going to use a reference Pose or JointState?  default: false
    joint_target_topic:     "/robot1/interp_joint_pos_target"   # incoming joints setpoint topic 
    pose_target:            "/robot1/interp_target_cart_pose"   # incoming pose setpoint topic
    
    robot_base_frame  : linear_axis
    robot_tip_frame   : KR210_1_A6



robot1_plan_hw:
  type: cnr/control/TopicRobotHW
  appenders: [file, screen]
  levels: [trace, info]
  pattern_layout: "[%5p][%d{HH:mm:ss,SSS}][%M:%L][%c] %m%n"
  file_name: "robot1_plan_hw"
  
  joint_names:
  - kr210_1_linear_axis_joint
  - kr210_1_joint_1
  - kr210_1_joint_2
  - kr210_1_joint_3
  - kr210_1_joint_4
  - kr210_1_joint_5
  - kr210_1_joint_6

  base_link: "linear_axis"
  tool_link: "KR210_1_A6"
  robot_description_param: /robot_description
  robot_description_planning_param: /robot_description_planning

  feedback_joint_state_topic: /joint_states
  command_joint_state_topic:  /robot1/interp_joint_pos_target
  sampling_period: 0.005
  diagnostic_period: 0.1
  feedback_joint_state_timeout: 20
  maximum_missing_cycles: 100

  remap_source_args:
  - "/robot1_plan_hw/microint_r1/follow_joint_trajectory/cancel"
  - "/robot1_plan_hw/microint_r1/follow_joint_trajectory/feedback"
  - "/robot1_plan_hw/microint_r1/follow_joint_trajectory/goal"
  - "/robot1_plan_hw/microint_r1/follow_joint_trajectory/result"
  - "/robot1_plan_hw/microint_r1/follow_joint_trajectory/status"

  remap_target_args:
  - "tez_1_moveit_lab/follow_joint_trajectory/cancel"
  - "tez_1_moveit_lab/follow_joint_trajectory/feedback"
  - "tez_1_moveit_lab/follow_joint_trajectory/goal"
  - "tez_1_moveit_lab/follow_joint_trajectory/result"
  - "tez_1_moveit_lab/follow_joint_trajectory/status"

  microint_r1:
    type: "cnr/control/FollowJointTrajectoryPosVelEffController"
    controlled_joints: all
    interpolator: "thor/ThorPrefilter"
    regulator: "regulator/fake_regulator"
    spline_order: 1
