///////////////////////////////////////////////////////////////////////////////
// Rsi.h
#pragma once

#include "RsiReaderWriterInterfaces.h"

#include "string";

using namespace std;

class CRsi 
	: public ITComObject
	, public ITcADI
	, public ITcWatchSource
///<AutoGeneratedContent id="InheritanceList">
	, public IRsi
///</AutoGeneratedContent>
{
public:
	DECLARE_IUNKNOWN()
	DECLARE_IPERSIST(CID_RsiReaderWriterCRsi)
	DECLARE_ITCOMOBJECT_LOCKOP()
	DECLARE_ITCADI()
	DECLARE_ITCWATCHSOURCE()
	DECLARE_OBJPARAWATCH_MAP()
	DECLARE_OBJDATAAREA_MAP()

	CRsi();
	virtual	~CRsi();

///<AutoGeneratedContent id="InterfaceMembers">
	// IRsi
	virtual double TCOMAPI get_axis_1();
	virtual double TCOMAPI get_axis_2();
	virtual double TCOMAPI get_axis_3();
	virtual double TCOMAPI get_axis_4();
	virtual double TCOMAPI get_axis_5();
	virtual double TCOMAPI get_axis_6();
	virtual double TCOMAPI get_external_axis_1();
	virtual HRESULT TCOMAPI read_incoming_msg(ULONG nStr, char* pStr);
	virtual double TCOMAPI get_axis_1_setpoint();
	virtual double TCOMAPI get_axis_2_setpoint();
	virtual double TCOMAPI get_axis_3_setpoint();
	virtual double TCOMAPI get_axis_4_setpoint();
	virtual double TCOMAPI get_axis_5_setpoint();
	virtual double TCOMAPI get_axis_6_setpoint();
	virtual double TCOMAPI get_cartesian_x_setpoint();
	virtual double TCOMAPI get_cartesian_y_setpoint();
	virtual double TCOMAPI get_cartesian_z_setpoint();
	virtual double TCOMAPI get_cartesian_rot1_setpoint();
	virtual double TCOMAPI get_cartesian_rot2_setpoint();
	virtual double TCOMAPI get_cartesian_rot3_setpoint();
	virtual double TCOMAPI get_cartesian_x();
	virtual double TCOMAPI get_cartesian_y();
	virtual double TCOMAPI get_cartesian_z();
	virtual double TCOMAPI get_cartesian_rot1();
	virtual double TCOMAPI get_cartesian_rot2();
	virtual double TCOMAPI get_cartesian_rot3();
	virtual USHORT TCOMAPI write_msg(ULONG max_length_msg, char* msg, double ax1, double ax2, double ax3, double ax4, double ax5, double ax6, double external_axis1);
	virtual double TCOMAPI get_external_axis_1_setpoint();

///</AutoGeneratedContent>

protected:
	DECLARE_ITCOMOBJECT_SETSTATE_RT();

	// Tracing
	CTcTrace m_Trace;

	double ax1, ax2, ax3, ax4, ax5, ax6;
	double ax1_setpoint, ax2_setpoint, ax3_setpoint, ax4_setpoint, ax5_setpoint, ax6_setpoint;
	double external_axis1;
	double x, y, z, rot1, rot2, rot3;
	double x_setpoint, y_setpoint, z_setpoint, rot1_setpoint, rot2_setpoint, rot3_setpoint;
	double external_axis1_setpoint;
	uint32_t ipoc;


	bool read_cartesian_based_tag(const string& msg, const string& tag, double& x, double& y, double& z, double& rot1, double& rot2, double& rot3);
	bool find_substring(const string& msg, const string& target, int& position, int start_index = 0, int end_index = -1);
	bool read_joint_based_tag(const string& msg, const string tag, double& ax1, double& ax2, double& ax3, double& ax4, double& ax5, double& ax6);
	bool read_tag_no_arg_uint(const string& msg, const string& tag, uint32_t& value);
	bool read_external_axis_based_tag(const string& msg, const string tag, double& e_axis1);

///<AutoGeneratedContent id="Members">
	TcTraceLevel m_TraceLevelMax;
///</AutoGeneratedContent>
};
