///////////////////////////////////////////////////////////////////////////////
// RsiReaderWriterServices.h

#pragma once

#include "TcServices.h"

const ULONG DrvID_RsiReaderWriter = 0x3F000000;
#define SRVNAME_RSIREADERWRITER "RsiReaderWriter"

///<AutoGeneratedContent id="ClassIDs">
const CTCID CID_RsiReaderWriterCRsi = {0xeb745b26,0xc68e,0x4ee7,{0x9e,0x8f,0x1d,0x06,0x26,0x0b,0x78,0xa8}};
///</AutoGeneratedContent>

///<AutoGeneratedContent id="ParameterIDs">
///</AutoGeneratedContent>

///<AutoGeneratedContent id="DataTypes">
///</AutoGeneratedContent>



///<AutoGeneratedContent id="DataAreaIDs">
///</AutoGeneratedContent>

///<AutoGeneratedContent id="InterfaceIDs">
#if !defined(_TC_IID_FC0258CE_5FC8_476C_9617_5A58D8BF5C9C_INCLUDED_)
#define _TC_IID_FC0258CE_5FC8_476C_9617_5A58D8BF5C9C_INCLUDED_
TCOM_DECL_INTERFACE("fc0258ce-5fc8-476c-9617-5a58d8bf5c9c", IRsi)
#endif // !defined(_TC_IID_FC0258CE_5FC8_476C_9617_5A58D8BF5C9C_INCLUDED_)

///</AutoGeneratedContent>

///<AutoGeneratedContent id="EventClasses">
///</AutoGeneratedContent>
