///////////////////////////////////////////////////////////////////////////////
// RsiReaderWriterClassFactory.cpp
#include "TcPch.h"
#pragma hdrstop

#include "RsiReaderWriterClassFactory.h"
#include "RsiReaderWriterServices.h"
#include "RsiReaderWriterVersion.h"
#include "Rsi.h"

BEGIN_CLASS_MAP(CRsiReaderWriterClassFactory)
///<AutoGeneratedContent id="ClassMap">
	CLASS_ENTRY_RT(CID_RsiReaderWriterCRsi, SRVNAME_RSIREADERWRITER "!CRsi", CRsi)
///</AutoGeneratedContent>
END_CLASS_MAP()

CRsiReaderWriterClassFactory::CRsiReaderWriterClassFactory() : CObjClassFactory()
{
	TcDbgUnitSetImageName(TCDBG_UNIT_IMAGE_NAME(SRVNAME_RSIREADERWRITER));
#if defined(TCDBG_UNIT_VERSION)
	TcDbgUnitSetVersion(TCDBG_UNIT_VERSION(RsiReaderWriter));
#endif //defined(TCDBG_UNIT_VERSION)
}

