///////////////////////////////////////////////////////////////////////////////
// RsiReaderWriterInterfaces.h

#pragma once

#include "TcInterfaces.h"
#include "TcIoInterfaces.h"
#include "TcRtInterfaces.h"
#include "RsiReaderWriterServices.h"

///<AutoGeneratedContent id="Interfaces">
#if !defined(_TC_TYPE_FC0258CE_5FC8_476C_9617_5A58D8BF5C9C_INCLUDED_)
#define _TC_TYPE_FC0258CE_5FC8_476C_9617_5A58D8BF5C9C_INCLUDED_
struct __declspec(novtable) IRsi : public ITcUnknown
{
	virtual double TCOMAPI get_axis_1()=0;
	virtual double TCOMAPI get_axis_2()=0;
	virtual double TCOMAPI get_axis_3()=0;
	virtual double TCOMAPI get_axis_4()=0;
	virtual double TCOMAPI get_axis_5()=0;
	virtual double TCOMAPI get_axis_6()=0;
	virtual double TCOMAPI get_external_axis_1()=0;
	virtual HRESULT TCOMAPI read_incoming_msg(ULONG nStr, char* pStr)=0;
	virtual double TCOMAPI get_axis_1_setpoint()=0;
	virtual double TCOMAPI get_axis_2_setpoint()=0;
	virtual double TCOMAPI get_axis_3_setpoint()=0;
	virtual double TCOMAPI get_axis_4_setpoint()=0;
	virtual double TCOMAPI get_axis_5_setpoint()=0;
	virtual double TCOMAPI get_axis_6_setpoint()=0;
	virtual double TCOMAPI get_cartesian_x_setpoint()=0;
	virtual double TCOMAPI get_cartesian_y_setpoint()=0;
	virtual double TCOMAPI get_cartesian_z_setpoint()=0;
	virtual double TCOMAPI get_cartesian_rot1_setpoint()=0;
	virtual double TCOMAPI get_cartesian_rot2_setpoint()=0;
	virtual double TCOMAPI get_cartesian_rot3_setpoint()=0;
	virtual double TCOMAPI get_cartesian_x()=0;
	virtual double TCOMAPI get_cartesian_y()=0;
	virtual double TCOMAPI get_cartesian_z()=0;
	virtual double TCOMAPI get_cartesian_rot1()=0;
	virtual double TCOMAPI get_cartesian_rot2()=0;
	virtual double TCOMAPI get_cartesian_rot3()=0;
	virtual USHORT TCOMAPI write_msg(ULONG max_length_msg, char* msg, double ax1, double ax2, double ax3, double ax4, double ax5, double ax6, double external_axis1)=0;
	virtual double TCOMAPI get_external_axis_1_setpoint()=0;
};
_TCOM_SMARTPTR_TYPEDEF(IRsi, IID_IRsi);
#endif // !defined(_TC_TYPE_FC0258CE_5FC8_476C_9617_5A58D8BF5C9C_INCLUDED_)

///</AutoGeneratedContent>
