robot2_mqtt_hw:
  type: "cnr/control/MQTTRobotHW"
  appenders      : [file, screen]
  levels         : [trace, debug]
  #pattern_layout : "[%5p][%d{HH:mm:ss,SSS}][%F:%M:%04L][%24c] %m%n"
  #pattern_layout : "[%5p][%d{HH:mm,SSS}][%M:%04L][%24c] %m%n"
  file_name      : robot2_mqtt_hw
  sampling_period: 0.004
  diagnostic_period: 0.1
  maximum_missing_cycles: 100
  feedback_joint_state_timeout: 10

  joint_names: 
  - kr210_2_linear_axis_joint
  - kr210_2_joint_1
  - kr210_2_joint_2
  - kr210_2_joint_3
  - kr210_2_joint_4
  - kr210_2_joint_5
  - kr210_2_joint_6

  base_link: "linear_axis"
  tool_link: "KR210_2_A6"
  robot_description_param: /robot_description
  robot_description_planning_param: /robot_description_planning
  kin_update_period: 0.1

  initial_position: [0.0, -1.57, 1.56, 1.57, 0.0, 0.0, 0.0] # [j1,j2,j3,j4,j5,j6,e0] last value is for the linear axis 
  
  use_delta_target_pos: false
  delta_pos_from_start: false
  
  use_real_robot: true
  verbose: false
  
  max_missing_cycles: 5
  
  goal_tolerance: [0.00001,0.001,0.001,0.001,0.001,0.001,0.001]
  
  #--- MQTT ---
  
  client_id: "robot2/MQTT_HW"
  host: 192.168.12.204    # drapebot
  #host: 172.31.1.11    # loris pc
  #host: localhost
  port: 1883
  
  feedback_mqtt_topic: "/robot_2/feedback"
  out_feedback_mqtt_topic: "/robot_2/ITR_feedback"
  command_mqtt_topic:  "/robot_2/command"
  nominal_trajectory_topic: /robot2/joint_pos_target
  # --- end ---
  

  remap_source_args:
  - "/robot2_mqtt_hw/js_pub_r2/joint_states"
  - "/robot2_mqtt_hw/cmd_pos"
  - "/robot2_mqtt_hw/old_pos"
  - "/robot2_mqtt_hw/delta_pos"
  remap_target_args:
  - "/robot2/joint_states"
  #- "/joint_states"  # TODO:: per uso singolo robot
  - "/cmd_pos_r2"
  - "/old_pos_r2"
  - "/delta_pos_r2"
  

  js_pub_r2:
    type: cnr/control/JointStatePublisher
    controlled_joints: all
    kin_update_period : 0.1


  p_j_r2:
    type: cnr/control/OpenLoopPositionController
    setpoint_topic_name: /robot2/joint_pos_target
    controlled_joints: all
    kin_update_period : 0.1





robot2_deformation_hw:
  type: cnr/control/TopicRobotHW
  appenders: [file, screen]
  levels: [trace, info]
  pattern_layout: "[%5p][%d{HH:mm:ss,SSS}][%M:%L][%c] %m%n"
  file_name: "robot2_deformation_hw"
  
  joint_names:   
  - kr210_2_linear_axis_joint
  - kr210_2_joint_1
  - kr210_2_joint_2
  - kr210_2_joint_3
  - kr210_2_joint_4
  - kr210_2_joint_5
  - kr210_2_joint_6

  base_link: "linear_axis"
  tool_link: "KR210_2_A6"
  robot_description_param: /robot_description
  robot_description_planning_param: /robot_description_planning

  feedback_joint_state_topic: /robot2/joint_states
  command_joint_state_topic:  /robot2/joint_pos_target
  sampling_period: 0.004
  diagnostic_period: 0.1
  feedback_joint_state_timeout: 20
  maximum_missing_cycles: 100

  deformation_ctrl_r2:
    type: "cnr/control/DeformationCtrl"
    controlled_joints: all
    kin_update_period: 0.008
    
    use_cartesian_reference: false                 # are you going to use a reference Pose or JointState?  default: false
    joint_target_topic:     "/robot2/interp_joint_pos_target"   # incoming joints setpoint topic 
    pose_target:            "/robot2/interp_target_cart_pose"   # incoming pose setpoint topic
    
    robot_base_frame  : linear_axis
    robot_tip_frame   : KR210_2_A6



robot2_plan_hw:
  type: cnr/control/TopicRobotHW
  appenders: [file, screen]
  levels: [trace, info]
  pattern_layout: "[%5p][%d{HH:mm:ss,SSS}][%M:%L][%c] %m%n"
  file_name: "robot2_plan_hw"
  
  joint_names:
  - kr210_2_linear_axis_joint
  - kr210_2_joint_1
  - kr210_2_joint_2
  - kr210_2_joint_3
  - kr210_2_joint_4
  - kr210_2_joint_5
  - kr210_2_joint_6

  base_link: "linear_axis"
  tool_link: "KR210_2_A6"
  robot_description_param: /robot_description
  robot_description_planning_param: /robot_description_planning

  feedback_joint_state_topic: /robot2/joint_states
  command_joint_state_topic:  /robot2/interp_joint_pos_target
  sampling_period: 0.004
  diagnostic_period: 0.1
  feedback_joint_state_timeout: 20
  maximum_missing_cycles: 100

  remap_source_args:
  - "/robot2_plan_hw/microint_r2/follow_joint_trajectory/cancel"
  - "/robot2_plan_hw/microint_r2/follow_joint_trajectory/feedback"
  - "/robot2_plan_hw/microint_r2/follow_joint_trajectory/goal"
  - "/robot2_plan_hw/microint_r2/follow_joint_trajectory/result"
  - "/robot2_plan_hw/microint_r2/follow_joint_trajectory/status"

  remap_target_args:
  - "tez_2_moveit_lab/follow_joint_trajectory/cancel"
  - "tez_2_moveit_lab/follow_joint_trajectory/feedback"
  - "tez_2_moveit_lab/follow_joint_trajectory/goal"
  - "tez_2_moveit_lab/follow_joint_trajectory/result"
  - "tez_2_moveit_lab/follow_joint_trajectory/status"

  microint_r2__:
    type: "cnr/control/FollowJointTrajectoryPosVelEffController"
    controlled_joints: all
    interpolator: "thor/ThorPrefilter"
    regulator: "regulator/fake_regulator"
    spline_order: 1
    
  microint_r2:
    type: "cnr/control/ScaledFJTPosController"
    controlled_joints: all
    
    
    
    
    
    
    
    
    
robot2_fake_hw:  # name of the hardware interface
  type           : cnr/control/FakeRobotHW  # type
  appenders      : [file, screen]  # logging information: the first one is stored in a file, the second one in the screen
  levels         : [trace, info]  # trace debug info warn error fatal
  pattern_layout : "[%5p][%d{HH:mm:ss,SSS}][%50M:%04L][%24c] %m%n"
  file_name      : robot2_fake_hw  # name of the file (it is saved in ~/.ros/)
  sampling_period: 0.004
  diagnostic_period: 0.1
  maximum_missing_cycles: 100
  feedback_joint_state_timeout: 10
  joint_names:  
  - kr210_2_linear_axis_joint
  - kr210_2_joint_1
  - kr210_2_joint_2
  - kr210_2_joint_3
  - kr210_2_joint_4
  - kr210_2_joint_5
  - kr210_2_joint_6
  
  base_link: "linear_axis"
  tool_link: "KR210_2_A6"
  robot_description_param: /robot_description
  robot_description_planning_param: /robot_description_planning

  initial_position: [5, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0]
  
  remap_source_args:
  - "/robot2_fake_hw/js_pub_r2/joint_states"
  
  remap_target_args:
  - "/robot2/joint_states"
  
  js_pub_r2:
    type: cnr/control/JointStatePublisher
    controlled_joints: all

  p_j_r2:
    type: cnr/control/OpenLoopPositionController
    setpoint_topic_name: /robot2/joint_pos_target
    controlled_joints: all
    kin_update_period : 0.1
  
